apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      app: todonodejs
      name: mysql
      template: todonodejs-mysql-persistent-template
    name: mysql
  spec:
    containers:
    - env:
      - name: MYSQL_ROOT_PASSWORD
        value: r00tpa55
      - name: MYSQL_USER
        value: user1
      - name: MYSQL_PASSWORD
        value: mypa55
      - name: MYSQL_DATABASE
        value: items
      image: quay.io/vcsamyiu/do180-mysql-57-rhel7
      name: mysql
      ports:
      - containerPort: 3306
        name: mysql
      volumeMounts:
      - mountPath: /var/lib/mysql/data
        name: db-volume
      - mountPath: /var/lib/mysql/init
        name: db-init
    volumes:
    - name: db-volume
      persistentVolumeClaim:
        claimName: dbclaim
    - name: db-init
      persistentVolumeClaim:
        claimName: dbinit
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      app: todonodejs
      name: todoapi
      template: todonodejs-mysql-persistent-template
    name: todoapi
  spec:
    containers:
    - env:
      - name: MYSQL_ENV_MYSQL_DATABASE
        value: items
      - name: MYSQL_ENV_MYSQL_USER
        value: user1
      - name: MYSQL_ENV_MYSQL_PASSWORD
        value: mypa55
      image: quay.io/vcsamyiu/do180-todonodejs
      name: todoapi
      ports:
      - containerPort: 30080
        name: nodejs-http
      resources:
        limits:
          cpu: "0.5"
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: todonodejs
      name: todoapi
      template: todonodejs-mysql-persistent-template
    name: todoapi
  spec:
    ports:
    - port: 30080
    selector:
      name: todoapi
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: todonodejs
      name: mysql
      template: todonodejs-mysql-persistent-template
    name: mysql
  spec:
    ports:
    - port: 3306
    selector:
      name: mysql
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: todonodejs
      template: todonodejs-mysql-persistent-template
    name: dbinit
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Mi
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: todonodejs
      template: todonodejs-mysql-persistent-template
    name: dbclaim
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Mi
kind: List
metadata: {}
